ui: mocha-bdd
browsers:
    - name: chrome
      version: 42..latest
    - name: firefox
      version: 41..latest
    - name: ie
      version: 9..latest
    - name: opera
      version: 29..latest
    - name: android
      version: -2..latest
    - name: safari
      version: -2..latest
browserify:
   - transform: coffeeify
   - options:
       extensions:
         - .coffee